#1)1num = 5    არასწორია 
num1 = 5
#2) points = "94     არასწორია 
points = "94"
#3) my-name = "gio"    არასწორია 
myname = "gio"
#4) num$ = 92     არასწორია 
num = 92
#5) num = xorbaladze     არასწორია 
lastname = "xorbaladze"
#6) name = luka      არასწორია 
name = "luka"
#7)user age = 15      არასწორია 
userage = 15
#8)message = გამარჯობა    არასწორია 
message = "გამარჯობა"      
#9)num = "73"    არასწორია  
num = 73
#10)user-points = 100     არასწორია 
user_points= 100